### PR TITLE
Updates matchRoutesToLocation to respect "exactly" flags set on routes.

### PR DESCRIPTION
**Pull request by ctrlplusb**

### CODE REVIEW

**Comment by ctrlplusb** [comment]
@markdalgleish thoughts?

I've found this useful personally.  Sometimes it pays to know if an exact match has occurred before executing any logic embedded within the routes.

**Comment by markdalgleish** [comment]
@ctrlplusb forgive my potential ignorance here, but I haven't personally seen this flag before—is it a standard thing?

**Comment by ctrlplusb** [comment]
Hi @markdalgleish 

Yeah, think of the equivalent when setting up standard `Match` instances:

```jsx
<Match pattern="/" exactly>
  <Foo />
</Match>
```

In this case we will only render `Foo` if the url location is `/`, but not for anything else (e.g. `/bar`).

Rendering the "home" route is the common use case.

**Comment by ctrlplusb** [comment]
So for our case, using this extensions library, we may want to only execute data prefetching on the `/` path if the user is specifically at that location.

**Comment by peter-mouland** [comment]
I would like to see this added too.

Currently, i have a route (`/game`) which has data-fetching `needs` (async on the server).  Using the function below, it shows that 2 routes are matched, when only one is correct.

```js
async function getContext(req, dispatch) {
  const { matchedRoutes, params } = matchRoutesToLocation(routes, { pathname: req.url });
  const promises = matchedRoutes
    .filter((route) => route.component.needs)
    .map((route) => {
      return route.component.needs.map((need) => dispatch(need(params)))
    });
  return await Promise.all(promises);
}
```

Here are the matched routes to help demonstrate.  You can see the homepage uses `exactly` meaning `/game` should not have been matched.

```js

  [ { name: 'homepage',
    exactly: true,
    pattern: '/',
    label: 'About React Lego',
    title: 'React Lego - About React Lego',
    component: [Function: Homepage] },
  { name: 'game',
    pattern: '/game/',
    label: 'Star Wars Trivia',
    title: 'React Lego - Star Wars Trivia',
    component: 
     { [Function: Connect]
       displayName: 'Connect(Game)',
       WrappedComponent: [Object],
       contextTypes: [Object],
       propTypes: [Object],
       needs: [Object] } } ]


```

**Comment by peter-mouland** [comment]
@ctrlplusb have you been able to get the data request to work?

I'm using redux and am clearly missing something... https://github.com/peter-mouland/react-lego/blob/koa-app/src/server/middleware/set-router-context.js

**Comment by ctrlplusb** [comment]
@markdalgleish

**Comment by ctrlplusb** [comment]
@ryanflorence

**Comment by markdalgleish** [comment]
Thanks for this PR. I'm adding some more tests before I plan to release it.

**Pull request merged**
